const employees = [
  {
    id: 1,
    firstName: "Ravi",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Task 1 for Employee 1",
        taskDescription: "Description for Task 1",
        taskDate: "2024-01-05",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Task 2 for Employee 1",
        taskDescription: "Description for Task 2",
        taskDate: "2024-01-10",
        category: "Testing",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Task 3 for Employee 1",
        taskDescription: "Description for Task 3",
        taskDate: "2024-01-15",
        category: "Design",
      },
    ],
    taskSummary: {
      active: 2,
      completed: 1,
      failed: 0,
      newTask: 2,
    },
  },
  {
    id: 2,
    firstName: "Amit",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Task 1 for Employee 2",
        taskDescription: "Description for Task 1",
        taskDate: "2024-01-07",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Task 2 for Employee 2",
        taskDescription: "Description for Task 2",
        taskDate: "2024-01-12",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Task 3 for Employee 2",
        taskDescription: "Description for Task 3",
        taskDate: "2024-01-20",
        category: "Management",
      },
    ],
    taskSummary: {
      active: 2,
      completed: 1,
      failed: 1,
      newTask: 1,
    },
  },
  {
    id: 3,
    firstName: "Rajesh",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Task 1 for Employee 3",
        taskDescription: "Description for Task 1",
        taskDate: "2024-01-05",
        category: "Testing",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Task 2 for Employee 3",
        taskDescription: "Description for Task 2",
        taskDate: "2024-01-10",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Task 3 for Employee 3",
        taskDescription: "Description for Task 3",
        taskDate: "2024-01-15",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Task 4 for Employee 3",
        taskDescription: "Description for Task 4",
        taskDate: "2024-01-18",
        category: "Testing",
      },
    ],
    taskSummary: {
      active: 3,
      completed: 2,
      failed: 0,
      newTask: 2,
    },
  },
  {
    id: 4,
    firstName: "Neha",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Task 1 for Employee 4",
        taskDescription: "Description for Task 1",
        taskDate: "2024-01-05",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Task 2 for Employee 4",
        taskDescription: "Description for Task 2",
        taskDate: "2024-01-10",
        category: "Development",
      },
      {
        active: true,
        newTask: true,
        completed: true,
        failed: false,
        taskTitle: "Task 3 for Employee 4",
        taskDescription: "Description for Task 3",
        taskDate: "2024-01-15",
        category: "Testing",
      },
    ],
    taskSummary: {
      active: 2,
      completed: 1,
      failed: 1,
      newTask: 2,
    },
  },
  {
    id: 5,
    firstName: "Priya",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Task 1 for Employee 5",
        taskDescription: "Description for Task 1",
        taskDate: "2024-01-07",
        category: "Management",
      },
      {
        active: true,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Task 2 for Employee 5",
        taskDescription: "Description for Task 2",
        taskDate: "2024-01-12",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Task 3 for Employee 5",
        taskDescription: "Description for Task 3",
        taskDate: "2024-01-18",
        category: "Development",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Task 4 for Employee 5",
        taskDescription: "Description for Task 4",
        taskDate: "2024-01-25",
        category: "Testing",
      },
    ],
    taskSummary: {
      active: 3,
      completed: 1,
      failed: 1,
      newTask: 2,
    },
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
